### ISSUE TITLE
Changes required for using non-quantized tflite files in MainActivity.java

### ISSUE THREAD

**Issue by sumanth-culli** [googlecodelabs/mlkit-android#5]
The [code][1] was written for quantised models and I'm trying to use unquantised model. I made the following changes as mentioned [here](https://github.com/tensorflow/tensorflow/issues/14719#issuecomment-348991399) to [MainActivity.java](https://github.com/googlecodelabs/mlkit-android/blob/master/custom-model/final/app/src/main/java/com/google/firebase/codelab/mlkit_custommodel/MainActivity.java) to overcome `Cannot convert an TensorFlowLite tensor with type FLOAT32 to a Java object of type [[B (which is compatible with the TensorFlowLite type UINT8)`.
     
    **Added these two lines**
        private static final int IMAGE_MEAN = 128;
        private static final float IMAGE_STD = 128.0f;

    **Changes made**
    Line 212   :byte[][] labelProbArray = task.getResult().<byte[][]>getOutput(0);
    .............................................................
    float[][] labelProbArray = task.getResult().<float[][]>getOutput(0);
 
   
    Line 235   :new AbstractMap.SimpleEntry<>(mLabelList.get(i), (labelProbArray[0][i]&0xff) / 255.0f));
    .............................................................
    new AbstractMap.SimpleEntry<>(mLabelList.get(i), (labelProbArray[0][i])));
    
    Line 288   :imgData.put((byte) ((val >> 16) & 0xFF));
    imgData.put((byte) ((val >> 8) & 0xFF));
    imgData.put((byte) (val & 0xFF));
    .............................................................
    imgData.putFloat((((val >> 16) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
    imgData.putFloat((((val >> 8) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);
    imgData.putFloat(((val & 0xFF)-IMAGE_MEAN)/IMAGE_STD);

But now I'm getting the following error:   **Note that `MainActivity.java:292` is `imgData.putFloat((((val >> 16) & 0xFF)-IMAGE_MEAN)/IMAGE_STD);`**

        --------- beginning of crash
    06-18 17:56:35.168 19375-19375/com.google.firebase.codelab.mlkit_custommodel E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.google.firebase.codelab.mlkit_custommodel, PID: 19375
        java.nio.BufferOverflowException
            at java.nio.Buffer.nextPutIndex(Buffer.java:514)
            at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:802)
            at com.google.firebase.codelab.mlkit_custommodel.MainActivity.convertBitmapToByteBuffer(MainActivity.java:292)
            at com.google.firebase.codelab.mlkit_custommodel.MainActivity.runModelInference(MainActivity.java:195)
            at com.google.firebase.codelab.mlkit_custommodel.MainActivity.access$000(MainActivity.java:63)
            at com.google.firebase.codelab.mlkit_custommodel.MainActivity$2.onClick(MainActivity.java:146)
            at android.view.View.performClick(View.java:6367)
            at android.view.View$PerformClick.run(View.java:25032)
            at android.os.Handler.handleCallback(Handler.java:790)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:164)
            at android.app.ActivityThread.main(ActivityThread.java:6753)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    06-18 17:56:35.173 19375-19375/com.google.firebase.codelab.mlkit_custommodel W/OPDiagnose: getService:OPDiagnoseService NULL
    06-18 17:56:35.177 19375-19454/com.google.firebase.codelab.mlkit_custommodel D/OSTracker: OS Event: crash

When I'm changing `DIM_BATCH_SIZE = 1` to `4` ([reference][2]) including the above changes, I'm getting              
`Cannot convert an TensorFlowLite tensor with type FLOAT32 to a Java object of type [[B (which is compatible with the TensorFlowLite type UINT8)`

When I'm multiplying `imgData` size by `4`([reference][3]), I'm getting    
`Input 0 should have 150528 bytes, but found 602112 bytes.`

  [1]: https://github.com/googlecodelabs/mlkit-android/blob/master/custom-model/final/app/src/main/java/com/google/firebase/codelab/mlkit_custommodel/MainActivity.java
  [2]: https://stackoverflow.com/questions/47761514/tensorflow-lite-pretrained-model-does-not-work-in-android-demo
  [3]: https://github.com/tensorflow/tensorflow/issues/14719#issuecomment-348991399

**Comment by sumanth-culli** [comment]
The discussion is [here](https://stackoverflow.com/questions/50923996/changes-required-for-using-non-quantized-tflite-files-in-mainactivity-java).
