### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by firefinchdev** [googlecodelabs/mlkit-android#60]
Using [MLKit's Android Barcode library (Bundled, v3)](https://developers.google.com/ml-kit/vision/barcode-scanning/android)
`com.google.mlkit:barcode-scanning:17.0.1`
From the limited users(that I currently have), I am experiencing the following crash on Firebase (repetitive):
1. Huawei 9A (MOA-LX9N)
2. Huawei Y9A (FRL-L22)
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/qrcodereader.barcodescanner.qrscanner.barcodereader.qrcode.barcode.qr.scanner.reader-28BTds1gUmGI_6g_4tY4uw==/base.apk"],nativeLibraryDirectories=[/data/app/qrcodereader.barcodescanner.qrscanner.barcodereader.qrcode.barcode.qr.scanner.reader-28BTds1gUmGI_6g_4tY4uw==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "libbarhopper_v3.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1668)
       at com.google.android.libraries.barhopper.BarhopperV3.<init>(BarhopperV3.java:5)
       at com.google.mlkit.vision.barcode.bundled.internal.zza.zzc(zza.java:36)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(zzbk.java:36)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(zzb.java:20)
       at android.os.Binder.transact(Binder.java:921)
       at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzc(zza.java:2)
       at com.google.android.gms.internal.measurement.zzbm.zzc$bridge(zzbm.java:2)
       at com.google.android.gms.internal.mlkit_vision_barcode.zznu.zze(zznu.java:3)
       at com.google.mlkit.vision.barcode.internal.zzl.zza(zzl.java:3)
       at com.google.mlkit.vision.barcode.internal.zzi.zzc(zzi.java:1)
       at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(MobileVisionBase.java:18)
       at com.google.mlkit.vision.common.internal.zzd.call(zzd.java:18)
       at com.google.android.gms.measurement.internal.zzfh.call$bridge(zzfh.java:18)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:28)
       at com.google.mlkit.common.sdkinternal.zzl.run(zzl.java:28)
       at com.google.android.gms.measurement.internal.zzjf.run$bridge(zzjf.java:28)
       at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:137)
       at com.google.android.gms.common.api.internal.zacm.run$bridge(zacm.java:137)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.zzi.run(zzi.java:2)
       at com.google.mlkit.common.sdkinternal.zzi.run$bridge(zzi.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:4)
       at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:4)
       at com.google.mlkit.common.sdkinternal.zzi.run$bridge(zzi.java:4)
       at java.lang.Thread.run(Thread.java:929)
```

I am not experienced enough with ndk, but I found a [stackoverflow link](https://stackoverflow.com/questions/27186726/java-lang-unsatisfiedlinkerror-dalvik-system-pathclassloader) that might be useful.

Can you please look into this, if it is a OEM device specific error or a bug with mlkit itself?...
Thanks

**Comment by firefinchdev** [comment]
Found more exceptions on
Pixel 3 XL (Android 9)
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/qrcodereader.barcodescanner.qrscanner.barcodereader.qrcode.barcode.qr.scanner.reader-MOvHVQ3Vaz-gYeG6uROlsA==/base.apk"],nativeLibraryDirectories=[/data/app/qrcodereader.barcodescanner.qrscanner.barcodereader.qrcode.barcode.qr.scanner.reader-MOvHVQ3Vaz-gYeG6uROlsA==/lib/arm64, /system/lib64]]] couldn't find "libbarhopper_v3.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
       at java.lang.System.loadLibrary(System.java:1669)
       at com.google.android.libraries.barhopper.BarhopperV3.<init>(BarhopperV3.java:5)
       at com.google.mlkit.vision.barcode.bundled.internal.zza.zzc(zza.java:36)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(zzbk.java:36)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(zzb.java:20)
       at android.os.Binder.transact(Binder.java:667)
       at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzc(zza.java:2)
       at com.google.android.gms.internal.measurement.zzbm.zzc$bridge(zzbm.java:2)
       at com.google.android.gms.internal.mlkit_vision_barcode.zznu.zze(zznu.java:3)
       at com.google.mlkit.vision.barcode.internal.zzl.zza(zzl.java:3)
       at com.google.mlkit.vision.barcode.internal.zzi.zzc(zzi.java:1)
       at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(MobileVisionBase.java:18)
       at com.google.mlkit.vision.common.internal.zzd.call(zzd.java:18)
       at com.google.android.gms.measurement.internal.zzfh.call$bridge(zzfh.java:18)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(ModelResource.java:28)
       at com.google.mlkit.common.sdkinternal.zzl.run(zzl.java:28)
       at com.google.android.gms.measurement.internal.zzjf.run$bridge(zzjf.java:28)
       at com.google.mlkit.common.sdkinternal.zzp.run(zzp.java:137)
       at com.google.android.gms.common.api.internal.zacm.run$bridge(zacm.java:137)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(MlKitThreadPool.java:2)
       at com.google.mlkit.common.sdkinternal.zzi.run(zzi.java:2)
       at com.google.mlkit.common.sdkinternal.zzi.run$bridge(zzi.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(MlKitThreadPool.java:4)
       at com.google.mlkit.common.sdkinternal.zzj.run(zzj.java:4)
       at com.google.mlkit.common.sdkinternal.zzi.run$bridge(zzi.java:4)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by pradyandroiddev** [comment]
Hi. This issue still exist! Found this issue on Xiaomi poco F3 - version 17.0.3.

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~0GSSiAoyrKEkXRCD-0z76A==/blibli.mobile.commerce-BZ-gYrPDqfnkaamr6ojvVA==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libbarhopper_v3.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.google.android.libraries.barhopper.BarhopperV3.<init>(com.google.mlkit:barcode-scanning@@17.0.3:1)
       at com.google.mlkit.vision.barcode.bundled.internal.zzb.zzc(com.google.mlkit:barcode-scanning@@17.0.3:1)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzbk.zza(com.google.mlkit:barcode-scanning@@17.0.3:9)
       at com.google.android.gms.internal.mlkit_vision_barcode_bundled.zzb.onTransact(com.google.mlkit:barcode-scanning@@17.0.3:3)
       at android.os.Binder.transact(Binder.java:1169)
       at com.google.android.gms.internal.mlkit_vision_barcode.zza.zzc(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:2)
       at com.google.android.gms.internal.mlkit_vision_barcode.zzqb.zze(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:2)
       at com.google.mlkit.vision.barcode.internal.zzl.zza(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:3)
       at com.google.mlkit.vision.barcode.internal.zzi.zze(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:3)
       at com.google.mlkit.vision.barcode.internal.zzi.run(com.google.android.gms:play-services-mlkit-barcode-scanning@@18.1.0:1)
       at com.google.mlkit.vision.common.internal.MobileVisionBase.zza(com.google.mlkit:vision-common@@17.3.0:2)
       at com.google.mlkit.vision.common.internal.zza.call(com.google.mlkit:vision-common@@17.3.0:4)
       at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.6.0:8)
       at com.google.mlkit.common.sdkinternal.zzn.run(com.google.mlkit:common@@18.6.0:10)
       at com.google.mlkit.common.sdkinternal.zzt.run(com.google.mlkit:common@@18.6.0:2)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.6.0:4)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.6.0:1)
       at com.google.mlkit.common.sdkinternal.zzk.run(com.google.mlkit:common@@18.6.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.6.0:2)
       at com.google.mlkit.common.sdkinternal.zzi.run(com.google.mlkit:common@@18.6.0:2)
       at java.lang.Thread.run(Thread.java:1012)
```
